### PR TITLE
feat: Sidebar Component

### PR DESCRIPTION
**Pull request by tushartiwari7**
Sidebar contains links to all the components of the library. (Hardcoded Screen only)

### CODE REVIEW

**Comment by rkapoor10** [comment]
good to go.

**Review by anjali1102 — APPROVED** [review]
I really liked how you structure your files.
Pretty Clean!

**Review by anjali1102 — APPROVED** [review]
I really liked how you structure your files.
Pretty Clean!

**Review by anjali1102 — APPROVED** [review]
I really liked how you structure your files.
Pretty Clean!

**Pull request merged**
